trainer: experimental.adeesh.denoising.trainers.sde_denoising_trainer.DenoisingTrainer

dataset:
  - src: /home/jovyan/repos/ocp-modeling/data/is2re/all/train
  #- src: /home/jovyan/shared-scratch/adeesh/data/oc20_dense/lmdbs_train_subsplits/train
  #- src: /home/jovyan/shared-scratch/adeesh/data/oc20_dense/lmdbs/train_oc20dense_rs_overfit
    normalize_labels: False
  # - src: data/is2re/all/val_id/data.lmdb

logger:
  name: wandb
  project: ads_COM_diff

task:
  dataset: lmdb
  train_on_free_atoms: True
  eval_on_free_atoms: True
  relaxation_steps: 300
  relaxation_fmax: 0.01
  relax_dataset: 
        src: /home/jovyan/shared-scratch/adeesh/data/oc20_dense/lmdbs/rand1_I0.1
        #src: /home/jovyan/shared-scratch/adeesh/data/oc20_dense/lmdbs_corr/train_oc20dense_rs
        #src: /home/jovyan/shared-scratch/adeesh/denoising/com_denoising/com-xy_std0.01-10_numstep50x10_lr1.e-4_allcorr/final_struct_lmdb
        #src: /home/jovyan/shared-scratch/adeesh/data/oc20_dense/lmdbs_train_subsplits/val
  relax_opt:
        maxstep: 0.04
        memory: 50
        damping: 1.0
        alpha: 70.0
        #traj_dir: /home/jovyan/shared-scratch/adeesh/denoising/com_sde/bysigma_lmdbcorr_std0.1-10_numstep100_sample1
        traj_dir: /home/jovyan/shared-scratch/adeesh/denoising/overfit_sde/rand1I0.1_std0.1-10_numstep100_seed0
hide_eval_progressbar: False

model:
  name: experimental.adeesh.denoising.models.gemnet_oc.GemNetOC
  num_spherical: 7
  num_radial: 128
  num_blocks: 4
  emb_size_atom: 256
  emb_size_edge: 512
  emb_size_trip_in: 64
  emb_size_trip_out: 64
  emb_size_quad_in: 32
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  num_before_skip: 2
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  num_output_afteratom: 3
  cutoff: 12.0
  cutoff_qint: 12.0
  cutoff_aeaint: 12.0
  cutoff_aint: 12.0
  max_neighbors: 30
  max_neighbors_qint: 8
  max_neighbors_aeaint: 20
  max_neighbors_aint: 1000
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  sbf:
    name: legendre_outer
  extensive: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: configs/s2ef/all/gemnet/scaling_factors/gemnet-oc.pt

  regress_forces: True
  direct_forces: True
  forces_coupled: False

  quad_interaction: True
  atom_edge_interaction: True
  edge_atom_interaction: True
  atom_interaction: True

  num_atom_emb_layers: 2
  num_global_out_layers: 2
  qint_tags: [1, 2]
  so3_denoising: True

optim:
  batch_size:                   16        # 6
  eval_batch_size:              16         # 6
  grad_accumulation_steps:      1         # gradient accumulation: effective batch size = `grad_accumulation_steps` * `batch_size` * (num of GPUs)
  load_balancing: atoms
  num_workers: 4
  lr_initial:                   4.e-4     # [0.0002, 0.0004], eSCN uses 0.0008 for batch size 96

  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.001
  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2 #0.2
    warmup_epochs: 4
    lr_min_factor: 0.01         #

  max_epochs: 10000000
  force_coefficient: 100
  energy_coefficient: 2
  clip_grad_norm: 100
  ema_decay: 0.999
  loss_energy: mae
  loss_force: l2mae

  # for denoising positions
  use_denoising_pos:            True
  denoising_pos_params:         
    prob:                       1      # probability to switch between denoising positions and S2EF
    fixed_noise_std:            False
    num_steps:                  100
    ads_std_low:                0.1      # lowest standard deviation of Gaussian noise for each xyz component
    ads_std_high:               10
    rot_std_low:               0.01
    rot_std_high:              1.55
    free_std_low:            0.01
    free_std_high:           0.1
    sample_low_forces:         True
    only_langevin:             True
  denoising_pos_coefficient:    1